#ifndef ENCODER_H
#define ENCODER_H

#include "zf_common_headfile.h"

#define ENCODER_1 (QTIMER1_ENCODER1)//RF
#define ENCODER_1_A (QTIMER1_ENCODER1_CH1_C0)
#define ENCODER_1_B (QTIMER1_ENCODER1_CH2_C1)

#define ENCODER_2 (QTIMER1_ENCODER2)//LF
#define ENCODER_2_A (QTIMER1_ENCODER2_CH1_C2)
#define ENCODER_2_B (QTIMER1_ENCODER2_CH2_C24)

#define ENCODER_3 (QTIMER2_ENCODER1)//LB
#define ENCODER_3_A (QTIMER2_ENCODER1_CH1_C3)
#define ENCODER_3_B (QTIMER2_ENCODER1_CH2_C4)

#define ENCODER_4 (QTIMER2_ENCODER2)//RB
#define ENCODER_4_A (QTIMER2_ENCODER2_CH1_C5)
#define ENCODER_4_B (QTIMER2_ENCODER2_CH2_C25)

void encoder_init(void);

#endif
